version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
build:
  docker:
    - image: circleci/node:12.0-browsers
  steps:
    - add_ssh_keys:
        fingerprints:
          - "e3:56:4b:3d:1c:58:a6:f9:7d:24:0a:90:01:77:aa:fb"
    - checkout
    - run:
        name: Prepare
        command: npm install
    - run:
        name: Build
        command: npm run build
    - run:
        name: Unit Test (with coverage)
        command: npm run coverage
    - run:
        name: Build Storybook
        command: npm run build-storybook
    - run:
        name: Prepare demo
        command: ./scripts/demo.sh
    - persist_to_workspace:
        root: .
        paths:
          - ./demo
          - ./storybook-static

workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          name: Cypress tests on Firefox
          requires:
            - cypress/install 
          browser: firefox
          start: npm run dev
          wait-on: http://0.0.0.0:8080
          command: npm run cypress:run
          group: firefox
      - cypress/run:
          name: Cypress tests on Chrome
          requires:
            - cypress/install 
          browser: chrome
          start: npm run dev
          wait-on: http://0.0.0.0:8080
          command: npm run cypress:run
          group: chrome
      - cypress/run:
          name: Cypress tests on Electron
          requires:
            - cypress/install 
          browser: electron
          start: npm run dev
          wait-on: http://0.0.0.0:8080
          command: npm run cypress:run
          group: electron